# $NetBSD$

DISTNAME=	{{{distName}}}
CATEGORIES=	{{{categories}}}

MAINTAINER=	{{{maintainer}}}
COMMENT=	{{{comment}}}
LICENSE=	{{{license}}}

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
