# $NetBSD$

DISTNAME=	{{distName}}
CATEGORIES=	{% for cat in categories %}{{ cat.value }}{% if !cat.last %} {% endif %}{% endfor %}

MAINTAINER=	{{maintainer}}
COMMENT=	{{comment}}
LICENSE=	{{license}}

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
