# $NetBSD$

DISTNAME=	{{{DISTNAME}}}
CATEGORIES=	{{{CATEGORIES}}}

MAINTAINER=	{{{MAINTAINER}}}
COMMENT=	{{{COMMENT}}}
LICENSE=	{{{LICENSE}}}

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
